### ISSUE TITLE
[FEATURE] support play_media action?

### ISSUE THREAD

**Issue by bfg100k** [cavefire/Bose-Homeassistant#15]
Thanks for making this integration. I got it working with my BOSE soundbar 600 but it appears that the play_media function is not supported? i.e. my HA script below returns an error.

```yaml
alias: Play 933 on Bose Soundbar
sequence:
  - target:
      entity_id: media_player.bose_smart_soundbar_6003227
    data:
      media_content_id: media-source://radio_browser/31710261-0b76-11e9-a80b-52543be04c81
      media_content_type: audio/aac
    metadata:
      title: 933 Radio
      thumbnail: http://www.meradio.sg/static/apple-icon-120x120.png
      media_class: music
      children_media_class: null
      navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://radio_browser
        - media_content_type: music
          media_content_id: media-source://radio_browser/country/SG
    action: media_player.play_media
mode: single
icon: mdi:radio
```
