### ISSUE TITLE
[FEATURE] Volume does not show up as an entiry

### ISSUE THREAD

**Issue by chrisjschultz** [cavefire/Bose-Homeassistant#5]
**Is your feature request related to a problem? Please describe.**
It would be really useful to have volume control as an entity so it can be added directly to a dash board for a quick way to change volume all all devices esp when in a group.

**Describe the solution you'd like**
Expose volume as an entity

**Additional context**
Might be useful to have the device name so how as part of the entity. Not a common thing tho across ha device integrations

**Comment by cavefire** [comment]
Hey @chrisjschultz,

I see your point, but I don't want to add redundant entities to a device.
You might want to check out [lovelace-mushroom](https://github.com/piitaya/lovelace-mushroom) and configure a slider that way: 
```yaml
type: custom:mushroom-media-player-card
entity: media_player.bose_soundbar_ultra
show_volume_level: false
volume_controls:
  - volume_set
layout: horizontal
secondary_info: none
```

Or you might give [mini-media-player](https://github.com/kalkih/mini-media-player) a try. Seems promising as well.
